language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
install:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc --verbose --all
  - cargo bench --verbose --all -- --test
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
