[package]
name = "pdatastructs"
version = "0.3.0"
authors = ["Marco Neumann <marco@crepererum.net>"]
license = "MIT"
keywords = ["bloomfilter", "countminsketch", "hyperloglog", "reservoirsampling", "topk"]
categories = ["data-structures"]
description = "Simple probabilistic data structures"
repository = "https://github.com/crepererum/pdatastructs.rs"
documentation = "https://docs.rs/pdatastructs/"
readme = "README.md"

[dependencies]
fixedbitset = "^0.1.9"
num-traits = "^0.2.4"
rand = "0.5"
