[package]
name = "pdatastructs"
version = "0.1.0"
authors = ["Marco Neumann <marco@crepererum.net>"]
license = "MIT"
keywords = ["bloomfilter", "hyperloglog"]
categories = ["data-structures"]
description = "Simple probabilistic data structures"
repository = "https://github.com/crepererum/pdatastructs.rs"
documentation = "https://docs.rs/pdatastructs/"
readme = "README.md"

[dependencies]
bit-vec = "0.4"
