[package]
name = "pdatastructs"
version = "0.4.0"
authors = ["Marco Neumann <marco@crepererum.net>"]
license = "MIT/Apache-2.0"
keywords = [
    "filter",
    "probabilistic",
    "sampling",
    "sketch",
]
categories = ["data-structures"]
description = "Simple probabilistic data structures"
repository = "https://github.com/crepererum/pdatastructs.rs"
documentation = "https://docs.rs/pdatastructs/"
readme = "README.md"

[dependencies]
bytecount = "0.3"
fixedbitset = "^0.1.9"
num-traits = "^0.2.4"
rand = "0.5"
succinct = "^0.4.4"
void = "1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "filters"
harness = false

[[bench]]
name = "hyperloglog"
harness = false
