name: CI


on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
    tags:
      - v*


jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all

      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --all

      - name: cargo bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --verbose --all -- --test
